# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rak/Documents/Corium

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rak/Documents/Corium

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rak/Documents/Corium/CMakeFiles /home/rak/Documents/Corium/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rak/Documents/Corium/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Corium

# Build rule for target.
Corium: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Corium
.PHONY : Corium

# fast build rule for target.
Corium/fast:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/build
.PHONY : Corium/fast

src/anim.obj: src/anim.cpp.obj

.PHONY : src/anim.obj

# target to build an object file
src/anim.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/anim.cpp.obj
.PHONY : src/anim.cpp.obj

src/anim.i: src/anim.cpp.i

.PHONY : src/anim.i

# target to preprocess a source file
src/anim.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/anim.cpp.i
.PHONY : src/anim.cpp.i

src/anim.s: src/anim.cpp.s

.PHONY : src/anim.s

# target to generate assembly for a file
src/anim.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/anim.cpp.s
.PHONY : src/anim.cpp.s

src/audio.obj: src/audio.cpp.obj

.PHONY : src/audio.obj

# target to build an object file
src/audio.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/audio.cpp.obj
.PHONY : src/audio.cpp.obj

src/audio.i: src/audio.cpp.i

.PHONY : src/audio.i

# target to preprocess a source file
src/audio.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/audio.cpp.i
.PHONY : src/audio.cpp.i

src/audio.s: src/audio.cpp.s

.PHONY : src/audio.s

# target to generate assembly for a file
src/audio.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/audio.cpp.s
.PHONY : src/audio.cpp.s

src/game/entity/entity.obj: src/game/entity/entity.cpp.obj

.PHONY : src/game/entity/entity.obj

# target to build an object file
src/game/entity/entity.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/entity/entity.cpp.obj
.PHONY : src/game/entity/entity.cpp.obj

src/game/entity/entity.i: src/game/entity/entity.cpp.i

.PHONY : src/game/entity/entity.i

# target to preprocess a source file
src/game/entity/entity.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/entity/entity.cpp.i
.PHONY : src/game/entity/entity.cpp.i

src/game/entity/entity.s: src/game/entity/entity.cpp.s

.PHONY : src/game/entity/entity.s

# target to generate assembly for a file
src/game/entity/entity.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/entity/entity.cpp.s
.PHONY : src/game/entity/entity.cpp.s

src/game/entity/player.obj: src/game/entity/player.cpp.obj

.PHONY : src/game/entity/player.obj

# target to build an object file
src/game/entity/player.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/entity/player.cpp.obj
.PHONY : src/game/entity/player.cpp.obj

src/game/entity/player.i: src/game/entity/player.cpp.i

.PHONY : src/game/entity/player.i

# target to preprocess a source file
src/game/entity/player.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/entity/player.cpp.i
.PHONY : src/game/entity/player.cpp.i

src/game/entity/player.s: src/game/entity/player.cpp.s

.PHONY : src/game/entity/player.s

# target to generate assembly for a file
src/game/entity/player.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/entity/player.cpp.s
.PHONY : src/game/entity/player.cpp.s

src/game/game.obj: src/game/game.cpp.obj

.PHONY : src/game/game.obj

# target to build an object file
src/game/game.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/game.cpp.obj
.PHONY : src/game/game.cpp.obj

src/game/game.i: src/game/game.cpp.i

.PHONY : src/game/game.i

# target to preprocess a source file
src/game/game.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/game.cpp.i
.PHONY : src/game/game.cpp.i

src/game/game.s: src/game/game.cpp.s

.PHONY : src/game/game.s

# target to generate assembly for a file
src/game/game.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/game.cpp.s
.PHONY : src/game/game.cpp.s

src/game/gameInput.obj: src/game/gameInput.cpp.obj

.PHONY : src/game/gameInput.obj

# target to build an object file
src/game/gameInput.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/gameInput.cpp.obj
.PHONY : src/game/gameInput.cpp.obj

src/game/gameInput.i: src/game/gameInput.cpp.i

.PHONY : src/game/gameInput.i

# target to preprocess a source file
src/game/gameInput.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/gameInput.cpp.i
.PHONY : src/game/gameInput.cpp.i

src/game/gameInput.s: src/game/gameInput.cpp.s

.PHONY : src/game/gameInput.s

# target to generate assembly for a file
src/game/gameInput.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/gameInput.cpp.s
.PHONY : src/game/gameInput.cpp.s

src/game/gameRender.obj: src/game/gameRender.cpp.obj

.PHONY : src/game/gameRender.obj

# target to build an object file
src/game/gameRender.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/gameRender.cpp.obj
.PHONY : src/game/gameRender.cpp.obj

src/game/gameRender.i: src/game/gameRender.cpp.i

.PHONY : src/game/gameRender.i

# target to preprocess a source file
src/game/gameRender.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/gameRender.cpp.i
.PHONY : src/game/gameRender.cpp.i

src/game/gameRender.s: src/game/gameRender.cpp.s

.PHONY : src/game/gameRender.s

# target to generate assembly for a file
src/game/gameRender.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/gameRender.cpp.s
.PHONY : src/game/gameRender.cpp.s

src/game/obj/camera.obj: src/game/obj/camera.cpp.obj

.PHONY : src/game/obj/camera.obj

# target to build an object file
src/game/obj/camera.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/obj/camera.cpp.obj
.PHONY : src/game/obj/camera.cpp.obj

src/game/obj/camera.i: src/game/obj/camera.cpp.i

.PHONY : src/game/obj/camera.i

# target to preprocess a source file
src/game/obj/camera.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/obj/camera.cpp.i
.PHONY : src/game/obj/camera.cpp.i

src/game/obj/camera.s: src/game/obj/camera.cpp.s

.PHONY : src/game/obj/camera.s

# target to generate assembly for a file
src/game/obj/camera.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/obj/camera.cpp.s
.PHONY : src/game/obj/camera.cpp.s

src/game/obj/obj.obj: src/game/obj/obj.cpp.obj

.PHONY : src/game/obj/obj.obj

# target to build an object file
src/game/obj/obj.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/obj/obj.cpp.obj
.PHONY : src/game/obj/obj.cpp.obj

src/game/obj/obj.i: src/game/obj/obj.cpp.i

.PHONY : src/game/obj/obj.i

# target to preprocess a source file
src/game/obj/obj.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/obj/obj.cpp.i
.PHONY : src/game/obj/obj.cpp.i

src/game/obj/obj.s: src/game/obj/obj.cpp.s

.PHONY : src/game/obj/obj.s

# target to generate assembly for a file
src/game/obj/obj.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/obj/obj.cpp.s
.PHONY : src/game/obj/obj.cpp.s

src/game/tick.obj: src/game/tick.cpp.obj

.PHONY : src/game/tick.obj

# target to build an object file
src/game/tick.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/tick.cpp.obj
.PHONY : src/game/tick.cpp.obj

src/game/tick.i: src/game/tick.cpp.i

.PHONY : src/game/tick.i

# target to preprocess a source file
src/game/tick.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/tick.cpp.i
.PHONY : src/game/tick.cpp.i

src/game/tick.s: src/game/tick.cpp.s

.PHONY : src/game/tick.s

# target to generate assembly for a file
src/game/tick.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/tick.cpp.s
.PHONY : src/game/tick.cpp.s

src/game/world/map.obj: src/game/world/map.cpp.obj

.PHONY : src/game/world/map.obj

# target to build an object file
src/game/world/map.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/world/map.cpp.obj
.PHONY : src/game/world/map.cpp.obj

src/game/world/map.i: src/game/world/map.cpp.i

.PHONY : src/game/world/map.i

# target to preprocess a source file
src/game/world/map.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/world/map.cpp.i
.PHONY : src/game/world/map.cpp.i

src/game/world/map.s: src/game/world/map.cpp.s

.PHONY : src/game/world/map.s

# target to generate assembly for a file
src/game/world/map.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/game/world/map.cpp.s
.PHONY : src/game/world/map.cpp.s

src/gui/gui.obj: src/gui/gui.cpp.obj

.PHONY : src/gui/gui.obj

# target to build an object file
src/gui/gui.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/gui/gui.cpp.obj
.PHONY : src/gui/gui.cpp.obj

src/gui/gui.i: src/gui/gui.cpp.i

.PHONY : src/gui/gui.i

# target to preprocess a source file
src/gui/gui.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/gui/gui.cpp.i
.PHONY : src/gui/gui.cpp.i

src/gui/gui.s: src/gui/gui.cpp.s

.PHONY : src/gui/gui.s

# target to generate assembly for a file
src/gui/gui.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/gui/gui.cpp.s
.PHONY : src/gui/gui.cpp.s

src/input.obj: src/input.cpp.obj

.PHONY : src/input.obj

# target to build an object file
src/input.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/input.cpp.obj
.PHONY : src/input.cpp.obj

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh.obj: src/mesh.cpp.obj

.PHONY : src/mesh.obj

# target to build an object file
src/mesh.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/mesh.cpp.obj
.PHONY : src/mesh.cpp.obj

src/mesh.i: src/mesh.cpp.i

.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s

.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/phys/phys.obj: src/phys/phys.cpp.obj

.PHONY : src/phys/phys.obj

# target to build an object file
src/phys/phys.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/phys/phys.cpp.obj
.PHONY : src/phys/phys.cpp.obj

src/phys/phys.i: src/phys/phys.cpp.i

.PHONY : src/phys/phys.i

# target to preprocess a source file
src/phys/phys.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/phys/phys.cpp.i
.PHONY : src/phys/phys.cpp.i

src/phys/phys.s: src/phys/phys.cpp.s

.PHONY : src/phys/phys.s

# target to generate assembly for a file
src/phys/phys.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/phys/phys.cpp.s
.PHONY : src/phys/phys.cpp.s

src/phys/sys.obj: src/phys/sys.cpp.obj

.PHONY : src/phys/sys.obj

# target to build an object file
src/phys/sys.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/phys/sys.cpp.obj
.PHONY : src/phys/sys.cpp.obj

src/phys/sys.i: src/phys/sys.cpp.i

.PHONY : src/phys/sys.i

# target to preprocess a source file
src/phys/sys.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/phys/sys.cpp.i
.PHONY : src/phys/sys.cpp.i

src/phys/sys.s: src/phys/sys.cpp.s

.PHONY : src/phys/sys.s

# target to generate assembly for a file
src/phys/sys.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/phys/sys.cpp.s
.PHONY : src/phys/sys.cpp.s

src/render/renderer.obj: src/render/renderer.cpp.obj

.PHONY : src/render/renderer.obj

# target to build an object file
src/render/renderer.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/render/renderer.cpp.obj
.PHONY : src/render/renderer.cpp.obj

src/render/renderer.i: src/render/renderer.cpp.i

.PHONY : src/render/renderer.i

# target to preprocess a source file
src/render/renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/render/renderer.cpp.i
.PHONY : src/render/renderer.cpp.i

src/render/renderer.s: src/render/renderer.cpp.s

.PHONY : src/render/renderer.s

# target to generate assembly for a file
src/render/renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/render/renderer.cpp.s
.PHONY : src/render/renderer.cpp.s

src/render/shader/shader.obj: src/render/shader/shader.cpp.obj

.PHONY : src/render/shader/shader.obj

# target to build an object file
src/render/shader/shader.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/render/shader/shader.cpp.obj
.PHONY : src/render/shader/shader.cpp.obj

src/render/shader/shader.i: src/render/shader/shader.cpp.i

.PHONY : src/render/shader/shader.i

# target to preprocess a source file
src/render/shader/shader.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/render/shader/shader.cpp.i
.PHONY : src/render/shader/shader.cpp.i

src/render/shader/shader.s: src/render/shader/shader.cpp.s

.PHONY : src/render/shader/shader.s

# target to generate assembly for a file
src/render/shader/shader.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/render/shader/shader.cpp.s
.PHONY : src/render/shader/shader.cpp.s

src/resource.res: src/resource.rc.res

.PHONY : src/resource.res

# target to build an object file
src/resource.rc.res:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/resource.rc.res
.PHONY : src/resource.rc.res

src/sprite.obj: src/sprite.cpp.obj

.PHONY : src/sprite.obj

# target to build an object file
src/sprite.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/sprite.cpp.obj
.PHONY : src/sprite.cpp.obj

src/sprite.i: src/sprite.cpp.i

.PHONY : src/sprite.i

# target to preprocess a source file
src/sprite.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/sprite.cpp.i
.PHONY : src/sprite.cpp.i

src/sprite.s: src/sprite.cpp.s

.PHONY : src/sprite.s

# target to generate assembly for a file
src/sprite.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/sprite.cpp.s
.PHONY : src/sprite.cpp.s

src/texture.obj: src/texture.cpp.obj

.PHONY : src/texture.obj

# target to build an object file
src/texture.cpp.obj:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/texture.cpp.obj
.PHONY : src/texture.cpp.obj

src/texture.i: src/texture.cpp.i

.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s

.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/Corium.dir/build.make CMakeFiles/Corium.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Corium"
	@echo "... edit_cache"
	@echo "... src/anim.obj"
	@echo "... src/anim.i"
	@echo "... src/anim.s"
	@echo "... src/audio.obj"
	@echo "... src/audio.i"
	@echo "... src/audio.s"
	@echo "... src/game/entity/entity.obj"
	@echo "... src/game/entity/entity.i"
	@echo "... src/game/entity/entity.s"
	@echo "... src/game/entity/player.obj"
	@echo "... src/game/entity/player.i"
	@echo "... src/game/entity/player.s"
	@echo "... src/game/game.obj"
	@echo "... src/game/game.i"
	@echo "... src/game/game.s"
	@echo "... src/game/gameInput.obj"
	@echo "... src/game/gameInput.i"
	@echo "... src/game/gameInput.s"
	@echo "... src/game/gameRender.obj"
	@echo "... src/game/gameRender.i"
	@echo "... src/game/gameRender.s"
	@echo "... src/game/obj/camera.obj"
	@echo "... src/game/obj/camera.i"
	@echo "... src/game/obj/camera.s"
	@echo "... src/game/obj/obj.obj"
	@echo "... src/game/obj/obj.i"
	@echo "... src/game/obj/obj.s"
	@echo "... src/game/tick.obj"
	@echo "... src/game/tick.i"
	@echo "... src/game/tick.s"
	@echo "... src/game/world/map.obj"
	@echo "... src/game/world/map.i"
	@echo "... src/game/world/map.s"
	@echo "... src/gui/gui.obj"
	@echo "... src/gui/gui.i"
	@echo "... src/gui/gui.s"
	@echo "... src/input.obj"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh.obj"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/phys/phys.obj"
	@echo "... src/phys/phys.i"
	@echo "... src/phys/phys.s"
	@echo "... src/phys/sys.obj"
	@echo "... src/phys/sys.i"
	@echo "... src/phys/sys.s"
	@echo "... src/render/renderer.obj"
	@echo "... src/render/renderer.i"
	@echo "... src/render/renderer.s"
	@echo "... src/render/shader/shader.obj"
	@echo "... src/render/shader/shader.i"
	@echo "... src/render/shader/shader.s"
	@echo "... src/resource.res"
	@echo "... src/sprite.obj"
	@echo "... src/sprite.i"
	@echo "... src/sprite.s"
	@echo "... src/texture.obj"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

